<?xml version="1.0" encoding="UTF-8"?>
<questions id="1_0_0_6" name="Exceptions" nofquestions="1" nofsubcategories="0" filename="exceptions1_0_0_6.xml">
  <question id="1_0_0_6:0" type="0">
    <questiontext>&lt;br&gt;
    Consider the following class hierarchy and code fragment:&lt;br&gt;
&lt;br&gt;
&lt;img width='250' height='140' alt='image' 
    src='/data/images/hierarchy_exception.png'/&gt;&lt;br&gt;
&lt;br&gt;
1. try {&lt;br&gt;
2. // assume s is previously defined&lt;br&gt;
3. URL u = new URL(s);&lt;br&gt;
4. // in is an ObjectInputStream&lt;br&gt;
5. Object o = in.readObject();&lt;br&gt;
6. System.out.println(&amp;quot;Success&amp;quot;);&lt;br&gt;
7. }&lt;br&gt;
8. catch (MalformedURLException e) {&lt;br&gt;
9. System.out.println(&amp;quot;Bad URL&amp;quot;);&lt;br&gt;
10. }&lt;br&gt;
11. catch (StreamCorruptedException e) {&lt;br&gt;
12. System.out.println(&amp;quot;Bad file contents&amp;quot;);&lt;br&gt;
13. }&lt;br&gt;
14. catch (Exception e) {&lt;br&gt;
15. System.out.println(&amp;quot;General exception&amp;quot;);&lt;br&gt;
16. }&lt;br&gt;
17. finally {&lt;br&gt;
18. System.out.println(&amp;quot;Doing finally part&amp;quot;);&lt;br&gt;
19. }&lt;br&gt;
20. System.out.println(&amp;quot;Carrying on&amp;quot;);&lt;br&gt;
What lines are output if the constructor at line 3 throws a &lt;br&gt;
    MalformedURLException?&lt;br&gt;
$v$&lt;br&gt;
$v0$ Bad URL $v0end$&lt;br&gt;
$v1$ Bad URL, &lt;br&gt;
    Doing finally part,$v1end$&lt;br&gt;
$v2$ Bad URL, Doing finally part, Carrying &lt;br&gt;
    on$v2end$&lt;br&gt;
$v3$  Bad URL, Bad file contents, Doing finally part, &lt;br&gt;
    Carrying on$v3end$&lt;br&gt;
$vend$&lt;br&gt;</questiontext>
    <questionanswer>2</questionanswer>
  </question>
</questions>
